[project]
name = "paper-search"
version = "0.1.0"
description = "A tool for searching and retrieving academic papers from arXiv"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "httpx>=0.28.1",
    "mcp[cli]>=1.3.0",
]
